package mirantyJmartAK.jmart_android.model;

public enum ProductCategory {
    BOOK, KITCHEN, ELETRONIC, FASHION, GAMING, GADGET, MOTHERCARE, COSMETICS, HEALTHCARE, FURNITURE, JEWELRY, TOYS, FNB,
    STATIONERY, SPORTS, AUTOMOTIVE, PETCARE, ART_CRAFT, CARPENTRY, MISCELLANEOUS, PROPERTY, TRAVEL, WEDDING;
}